import { describe, expect, it } from 'vitest';

import { prepareExport, serializeMarkdown, type SemanticTree } from '@/src/core';

describe('safe export pipeline', () => {
  const tree: SemanticTree = {
    schemaVersion: 1,
    title: 'A *test* page',
    root: {
      role: 'page',
      children: [{
        role: 'textbox',
        name: 'Password',
        value: 'not-for-export',
        states: { required: true },
        children: [],
      }],
    },
  };

  it('serializes Markdown deterministically with escaped content and accurate size', () => {
    const result = serializeMarkdown(tree);

    expect(result).toEqual({
      format: 'markdown',
      content: '# A \\*test\\* page\n\n- **page**\n  - **textbox** — Password (value=`not-for-export`, required=true)\n',
      characterCount: result.content.length,
    });
  });

  it('always redacts after compression and reports format-relative metrics', () => {
    const result = prepareExport(tree, 'compact', 'markdown');

    expect(result.serialized.format).toBe('markdown');
    expect(result.serialized.content).toContain('[REDACTED]');
    expect(result.serialized.content).not.toContain('not-for-export');
    expect(result.characterCount).toBe(result.serialized.content.length);
    expect(result.approximateTokenCount).toBe(Math.ceil(result.characterCount / 4));
    expect(result.reductionRatio).toBeGreaterThanOrEqual(0);
    expect(result.redactionCount).toBe(1);
  });

  it('can export without redaction only when explicitly requested', () => {
    const result = prepareExport(tree, 'compact', 'semantic-text', false);

    expect(result.serialized.content).toContain('not-for-export');
    expect(result.serialized.content).not.toContain('[REDACTED]');
    expect(result.redactionCount).toBe(0);
  });

  it('measures compression against the redacted Without profile', () => {
    const result = prepareExport({
      schemaVersion: 1,
      root: {
        role: 'page',
        children: [{
          role: 'none',
          children: [{ role: 'button', name: 'Continue', children: [] }],
        }],
      },
    }, 'detailed', 'semantic-text');

    expect(result.reductionRatio).toBeGreaterThan(0);
    expect(result.reductionRatio).toBeLessThan(1);
  });

  it('includes redacted capture metadata in the export header', () => {
    const result = prepareExport({
      ...tree,
      title: 'Copy as Context synthetic test',
      sourceUrl: 'file:///tmp/copy-as-context-test.html?token=abcdefghijklmnop',
      capturedAt: '2026.09.27 17:12:55',
    }, 'detailed', 'semantic-text');

    expect(result.serialized.content).toContain(
      'Page: Copy as Context synthetic test\nURL: file:///tmp/copy-as-context-test.html?token=[REDACTED]\nCaptured: 2026.09.27 17:12:55\nGenerated by browser extension "Copy as Context" (created by Vitalii Shkrobatskyi)\n\npage',
    );
    expect(result.serialized.content).not.toContain('token=abcdefghijklmnop');
  });
});
