import { version } from '../../../package.json';
import { COMPRESSION_LEVELS, type CompressionLevel } from '..';

/** The low bit records the requested privacy setting; other bits encode the profile. */
export function renderExportAttribution(level?: CompressionLevel, redactSensitiveData = false): string {
  const settings = level === undefined ? ''
    : `/${COMPRESSION_LEVELS.indexOf(level) * 2 + Number(redactSensitiveData)}`;
  return `Generated by browser extension "Copy as Context" ${version}${settings} (created by V. Shkrobatskyi)`;
}
