import type { NodeStates, SemanticNode, SemanticTree, SerializedContext } from '..';

const STATE_ORDER: readonly (keyof NodeStates)[] = [
  'checked', 'selected', 'expanded', 'disabled', 'required', 'focusable', 'readOnly', 'focused',
];

/** Serializes an already-transformed semantic tree into stable, escaped Markdown. */
export function serializeMarkdown(tree: SemanticTree): SerializedContext {
  const lines: string[] = [];
  render(tree, lines);
  const content = `${lines.join('\n')}\n`;
  return { format: 'markdown', content, characterCount: content.length };
}

/** Measures the exact same output without accumulating tree lines or a full string. */
export function countMarkdownCharacters(tree: SemanticTree): number {
  return render(tree);
}

function render(tree: SemanticTree, lines?: string[]): number {
  const headers = lines ?? [];
  renderCaptureHeader(tree, headers);
  if (tree.title !== undefined && tree.sourceUrl === undefined && tree.capturedAt === undefined) {
    headers.push(`# ${escapeText(tree.title)}`, '');
  }
  const headerCount = headers.reduce((count, line) => count + line.length + 1, 0);
  return headerCount + renderNode(tree.root, 0, lines);
}

function renderCaptureHeader(tree: SemanticTree, lines: string[]): void {
  if (tree.sourceUrl === undefined && tree.capturedAt === undefined) return;

  lines.push(`**Page:** ${escapeText(tree.title ?? 'Untitled page')}`);
  lines.push(`**URL:** ${code(tree.sourceUrl ?? 'Unavailable')}`);
  lines.push(`**Captured:** ${escapeText(tree.capturedAt ?? 'Unavailable')}`);
  lines.push('Generated by browser extension "Copy as Context" (created by Vitalii Shkrobatskyi)', '');
}

function renderNode(node: SemanticNode, depth: number, lines?: string[]): number {
  const attributes: string[] = [];
  if (node.value !== undefined) attributes.push(`value=${code(node.value)}`);
  for (const state of STATE_ORDER) {
    const value = node.states?.[state];
    if (value !== undefined) attributes.push(`${state === 'readOnly' ? 'readonly' : state}=${value}`);
  }
  if (node.level !== undefined) attributes.push(`level=${node.level}`);
  if (node.href !== undefined) attributes.push(`href=${code(node.href)}`);

  const label = node.name === undefined ? '' : ` — ${escapeText(node.name)}`;
  const detail = attributes.length === 0 ? '' : ` (${attributes.join(', ')})`;
  const line = `${'  '.repeat(depth)}- **${escapeRole(node.role)}**${label}${detail}`;
  lines?.push(line);
  let characterCount = line.length + 1;
  for (const child of node.children) characterCount += renderNode(child, depth + 1, lines);
  return characterCount;
}

function escapeRole(value: string): string {
  return escapeText(value);
}

function escapeText(value: string): string {
  return value.replace(/[\\`*_{}\[\]()<>#+\-.!|]/gu, '\\$&').replace(/\r?\n/gu, ' ');
}

function code(value: string): string {
  return `\`${value.replace(/`/gu, '\\`').replace(/\r?\n/gu, ' ')}\``;
}
