import type { NodeStates, SemanticNode, SemanticTree, SerializedContext } from '..';

const STATE_ORDER: readonly (keyof NodeStates)[] = [
  'checked',
  'selected',
  'expanded',
  'disabled',
  'required',
  'focusable',
  'readOnly',
  'focused',
];

const SAFE_ROLE = /^\p{L}[\p{L}\p{N}_-]*$/u;

/** Serializes an already-transformed semantic tree without changing its structure. */
export function serializeSemanticText(tree: SemanticTree): SerializedContext {
  const lines: string[] = [];
  render(tree, lines);
  const content = `${lines.join('\n')}\n`;
  return { format: 'semantic-text', content, characterCount: content.length };
}

/** Measures the exact same output without accumulating tree lines or a full string. */
export function countSemanticTextCharacters(tree: SemanticTree): number {
  return render(tree);
}

function render(tree: SemanticTree, lines?: string[]): number {
  const headers = lines ?? [];
  renderCaptureHeader(tree, headers);
  const headerCount = headers.reduce((count, line) => count + line.length + 1, 0);
  return headerCount + renderNode(tree.root, 0, lines);
}

function renderCaptureHeader(tree: SemanticTree, lines: string[]): void {
  if (tree.sourceUrl === undefined && tree.capturedAt === undefined) return;

  lines.push(`Page: ${headerValue(tree.title, 'Untitled page')}`);
  lines.push(`URL: ${headerValue(tree.sourceUrl, 'Unavailable')}`);
  lines.push(`Captured: ${headerValue(tree.capturedAt, 'Unavailable')}`);
  lines.push('Generated by browser extension "Copy as Context" (created by Vitalii Shkrobatskyi)', '');
}

function headerValue(value: string | undefined, fallback: string): string {
  return (value ?? fallback).replace(/\r?\n/gu, ' ');
}

function renderNode(node: SemanticNode, depth: number, lines?: string[]): number {
  const fields = [renderRole(node.role)];
  if (node.name !== undefined) fields.push(quote(node.name));

  const attributes = renderAttributes(node);
  if (attributes.length > 0) fields.push(`[${attributes.join(', ')}]`);

  const line = `${'  '.repeat(depth)}${fields.join(' ')}`;
  lines?.push(line);
  let characterCount = line.length + 1;
  for (const child of node.children) characterCount += renderNode(child, depth + 1, lines);
  return characterCount;
}

function renderRole(role: string): string {
  return SAFE_ROLE.test(role) ? role : `role=${quote(role)}`;
}

function renderAttributes(node: SemanticNode): string[] {
  const attributes: string[] = [];

  if (node.value !== undefined) attributes.push(`value=${quote(node.value)}`);
  for (const state of STATE_ORDER) {
    const value = node.states?.[state];
    if (value !== undefined) attributes.push(`${renderStateName(state)}=${value}`);
  }
  if (node.level !== undefined) attributes.push(`level=${node.level}`);
  if (node.href !== undefined) attributes.push(`href=${quote(node.href)}`);

  return attributes;
}

function renderStateName(state: keyof NodeStates): string {
  return state === 'readOnly' ? 'readonly' : state;
}

function quote(value: string): string {
  return JSON.stringify(value)
    .replace(/\u2028/gu, '\\u2028')
    .replace(/\u2029/gu, '\\u2029');
}
